// @Shaon => I will change this list later

const InputList = [
	{
		name: 'productTitle',
		label: 'Product Name',
		type: 'text',
		required: true,
		placeholder: '',
	},
	{
		name: 'categories',
		label: 'Categories',
		type: 'text',
		required: true,
		options: [{ name: 'Bagg' }, { name: 'Computer' }, { name: 'Watch' }],
	},
	{ name: 'sku', label: 'SKU', type: 'text', placeholder: '', required: true },
	{
		name: 'unit',
		required: true,
		label: 'Unit',
		type: 'text',
		placeholder: '',
	},
	{
		name: 'item_group_id',
		label: 'item group id',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},

	{
		name: 'description',
		label: 'description',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'availability',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'condition',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{ name: 'price', type: 'text', required: true, placeholder: 'sadsadsawww' },
	{
		name: 'product_image',
		label: 'Product Image',
		type: 'file',
		required: true,
		placeholder: 'sadsadsawww',
	},

	{ name: 'link', type: 'text', required: true, placeholder: 'sadsadsawww' },
	{ name: 'brand', type: 'text', required: true, placeholder: 'sadsadsawww' },
	{
		name: 'google_product_category',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'fb_product_category',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'sale_price',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'sale_price_effective_date',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{ name: 'gender', type: 'text', required: true, placeholder: 'sadsadsawww' },
	{ name: 'color', type: 'text', required: true, placeholder: 'sadsadsawww' },
	{ name: 'size', type: 'text', required: true, placeholder: 'sadsadsawww' },
	{
		name: 'age_group',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'material',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{ name: 'pattern', type: 'text', required: true, placeholder: 'sadsadsawww' },
	{
		name: 'shipping',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'shipping_weight',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'style[0]',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'custom_label_1',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'Purchase Date',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'Product Name',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{ name: 'SKU', type: 'text', required: true, placeholder: 'sadsadsawww' },
	{
		name: 'Product Quantity',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'Buying Price Per Unit',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'Shipping & Other Cost Per Unit',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'Total Cost Per Unit',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'total_cost',
		label: 'Total Cost',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'available_products',
		label: 'Available Products',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
	{
		name: 'retail_proce',
		label: 'Retail Price',
		type: 'text',
		required: true,
		placeholder: 'sadsadsawww',
	},
]

export { InputList }
